Repository salesforce/design-system-react, pull requests merged in 2018-02, with the labels that each got.

#1275 Document child nodes of IconSettings
  components/icon-settings/index.jsx
Labels: documentation

#1243 Replace airbnb shape props with PropTypes.shape
  components/alert/index.jsx
  components/button-group/index.jsx
  components/combobox/combobox.jsx
  components/combobox/private/menu.jsx
  components/combobox/private/selected-listbox.jsx
  components/component-docs.json
  components/date-picker/date-picker.jsx
  components/forms/input/index.jsx
  components/menu-picklist/index.jsx
  components/pill/index.jsx
  components/progress-indicator/index.jsx
  components/progress-indicator/private/progress-bar.jsx
  components/progress-indicator/private/progress.jsx
  components/radio-button-group/__docs__/storybook-stories.jsx
  components/radio-button-group/__tests__/radio-button-group.browser-test.jsx
  components/radio-button-group/index.jsx
  components/radio-group/__docs__/storybook-stories.jsx
  components/radio-group/__tests__/radio-group.browser-test.jsx
  components/radio-group/index.jsx
  components/toast/index.jsx
  components/utilities/pill/index.jsx
  package.json
Labels: cla:signed

#1268 Export canUseDOM correctly to enable focus trap
  components/popover/__tests__/popover.browser-test.jsx
  components/tests-bundle.js
  karma.conf.js
  package.json
  tests/browser-tests-app.js
  tests/browser-tests.js
  tests/index.html
  utilities/__tests__/execution-environment.browser-test.jsx
  utilities/execution-environment.js
  webpack.config.test.js
Labels: accessibility, popover

#1272 Update prettier settings (JSON, package.json)
  .editorconfig
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  README.md
  app.json
  package-lock.json
  package.json
  tests/eslint-config-test.js
Labels: test task

#1287 Update Modal footer prop description
  components/modal/index.jsx
Labels: documentation

#1279 Add missing proptype and component descriptions
  components/accordion/panel.jsx
  components/avatar/index.jsx
  components/button-stateful/index.jsx
  components/button/index.jsx
  components/component-docs.json
  components/data-table/row-actions.jsx
  components/date-picker/date-picker.jsx
  components/forms/checkbox/index.jsx
  components/forms/input/index.jsx
  components/forms/textarea/index.jsx
  components/global-navigation-bar/link.jsx
  components/menu-dropdown/menu-dropdown.jsx
  components/page-header/index.jsx
  components/pill/index.jsx
  components/popover/popover.jsx
  components/split-view/listbox.jsx
  components/tabs/index.jsx
  components/tabs/panel.jsx
  components/tabs/private/tab-panel.jsx
  components/time-picker/index.jsx
  components/tree/index.jsx
  package.json
  scripts/local-qa.sh
  scripts/travis-ci.sh
  tests/component-docs-test.js
Labels: documentation

#1292 Switch to npx for npm scripts
  package.json
Labels: maintenance-task

#1290 Remove build/publish process for AMD tag
  scripts/dist.sh
  scripts/publish-to-git.js
Labels: maintenance-task

#1283 Combobox : Adding sub menu header and option to set width to width of menu
  .gitignore
  components/combobox/__docs__/site-stories.js
  components/combobox/__docs__/storybook-stories.jsx
  components/combobox/__examples__/base-inherit-menu-width.jsx
  components/combobox/__examples__/base-menu-separator.jsx
  components/combobox/__examples__/base-menu-subheader.jsx
  components/combobox/__examples__/snapshot/base-open-class-name.jsx
  components/combobox/__examples__/snapshot/base-open-menu-inheritWidthOf.jsx
  components/combobox/__examples__/snapshot/base-open-menu-sub-header.jsx
  components/combobox/__tests__/__snapshots__/combobox.snapshot-test.jsx.snap
  components/combobox/__tests__/combobox.snapshot-test.jsx
  components/combobox/add-subheadings.js
  components/combobox/combobox.jsx
  components/combobox/filter.js
  components/combobox/private/menu.jsx
  components/component-docs.json
  components/index.js
  components/lookup/lookup.jsx
  components/menu-dropdown/menu-dropdown.jsx
  components/menu-picklist/index.jsx
  components/utilities/dialog/index.jsx
  package-lock.json
  package.json
Labels: cla:signed

#1261 Implement no plus plus eslint rule
  components/combobox/__tests__/combobox.browser-test.jsx
  components/date-picker/private/calendar.jsx
  components/date-picker/private/week.jsx
  components/date-picker/private/year-picklist.jsx
  components/lookup/lookup.jsx
  components/progress-indicator/index.jsx
  components/radio-button-group/__tests__/radio-button-group.browser-test.jsx
  components/radio-group/__tests__/radio-group.browser-test.jsx
  components/tabs/index.jsx
  components/utilities/truncate/index.jsx
  utilities/keyboard-navigable-menu.js
  utilities/letter-key-code.js
  utilities/warning/low-priority-warning.js
Labels: maintenance-task
