Repository salesforce/design-system-react, pull requests merged in 2018-04, with the labels that each got.

#1317 Added SLDS Slider
  components/component-docs.json
  components/index.js
  components/site-stories.js
  components/slider/__docs__/site-stories.js
  components/slider/__docs__/storybook-stories.jsx
  components/slider/__examples__/base.jsx
  components/slider/__examples__/disabled.jsx
  components/slider/__examples__/error.jsx
  components/slider/__examples__/sizes-large.jsx
  components/slider/__examples__/sizes-medium.jsx
  components/slider/__examples__/sizes-small.jsx
  components/slider/__examples__/sizes-x-small.jsx
  components/slider/__examples__/sizes.jsx
  components/slider/__examples__/vertical.jsx
  components/slider/__tests__/__snapshots__/slider.snapshot-test.jsx.snap
  components/slider/__tests__/slider.browser-test.jsx
  components/slider/__tests__/slider.snapshot-test.jsx
  components/slider/index.jsx
  components/story-based-tests.js
  components/storybook-stories.js
  package.json
  utilities/constants.js
Labels: cla:signed

#1326 Allow importing lookup DefaultSectionDivider
  components/index.js
Labels: cla:signed

#1330 Fix typos
  CONTRIBUTING.md
  README.md
  RELEASENOTES.md
Labels: cla:signed, documentation

#1329 Fix bug with sortable causing focusable attribute to throw an error
  components/data-table/__tests__/__snapshots__/data-table.snapshot-test.jsx.snap
  components/data-table/private/header-cell.jsx
Labels: cla:signed

#1336 Clarify new component contribution section
  CONTRIBUTING.md
Labels: documentation

#1339 Trigger onOpen callback in Combobox
  components/combobox/__tests__/combobox.browser-test.jsx
  components/combobox/combobox.jsx
Labels: cla:signed

#1324 Learn more tooltip
  components/app-launcher/__tests__/tile.browser-test.jsx
  components/app-launcher/tile.jsx
  components/progress-indicator/__tests__/progress-indicator.browser-test.jsx
  components/progress-indicator/private/step.jsx
  components/slider/__tests__/slider.browser-test.jsx
  components/tooltip/__docs__/site-stories.js
  components/tooltip/__docs__/storybook-stories.jsx
  components/tooltip/__examples__/learn-more.jsx
  components/tooltip/__tests__/tooltip.browser-test.jsx
  components/tooltip/check-props.js
  components/tooltip/index.jsx
  utilities/__tests__/warnings.browser-test.jsx
  utilities/warning/deprecated-property-value.js
Labels: popover-tooltip

#1341 Focus input if menu was actually open and not just requested to close
  components/date-picker/date-picker.jsx
Labels: cla:signed
