Repository salesforce/design-system-react, pull requests merged in 2018-03, with the labels that each got.

#1298 Update Dropdown Menu children description
  components/menu-dropdown/menu-dropdown.jsx
Labels: documentation

#1299 Allowing input label of combobox to show as required (*).
  components/combobox/__docs__/storybook-stories.jsx
  components/combobox/__examples__/required-input-error-state.jsx
  components/combobox/__examples__/snapshot/base-label-required.jsx
  components/combobox/__tests__/__snapshots__/combobox.snapshot-test.jsx.snap
  components/combobox/__tests__/combobox.browser-test.jsx
  components/combobox/__tests__/combobox.snapshot-test.jsx
  components/combobox/combobox.jsx
  components/component-docs.json
Labels: cla:signed, outside-slds-pattern

#1308 fixes broken link to source of Inline Edit Inputs in docs
  package.json
Labels: cla:signed, documentation

#1311 replaced rendered input block to code block in docs
  components/forms/input/index.jsx
Labels: cla:signed

#1316 Fix prettier-eslint-cli warning in CI
  package-lock.json
  package.json
Labels: test task

#1306 Allow initial value for uncontrolled components
  components/button-group/__tests__/__snapshots__/button-group.snapshot-test.jsx.snap
  components/combobox/__tests__/__snapshots__/combobox.snapshot-test.jsx.snap
  components/component-docs.json
  components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
  components/forms/checkbox/__tests__/__snapshots__/checkbox.snapshot-test.jsx.snap
  components/forms/checkbox/index.jsx
  components/forms/input/index.jsx
  components/forms/input/private/inner-input.jsx
  components/forms/radio/index.jsx
  components/forms/textarea/index.jsx
  components/radio-button-group/__tests__/__snapshots__/radio-button-group.snapshot-test.jsx.snap
  components/radio-group/__tests__/__snapshots__/radio-group.snapshot-test.jsx.snap
Labels: cla:signed
