Repository salesforce/design-system-react, pull requests merged in 2018-05, with the labels that each got.

#1332 Change inline edit for a11y, eslint updates
  components/forms/input/inline.jsx
  package-lock.json
  package.json
Labels: cla:signed

#1344 Make hint an optional field for data table actions
  components/data-table/row-actions.jsx
Labels: cla:signed

#1323 Tree keyboard navigation
  components/tree/__tests__/tree.browser-test.jsx
  components/tree/index.jsx
  components/tree/private/branch.jsx
  components/tree/private/item.jsx
  package.json
Labels: accessibility, tree

#1349 Add a11y panel to storybook
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
Labels: test task

#1300 Include ES modules in NPM package
  .babelrc
  components/accordion/index.jsx
  components/avatar/index.jsx
  components/forms/radio/index.jsx
  components/radio-group/index.jsx
  components/radio-group/radio.jsx
  package-lock.json
  preset/index.js
  scripts/dist.sh
  scripts/npm-transform.js
Labels: current sprint, maintenance-task

#1351 Use npm ci for travis ci
  .travis.yml
  components/component-docs.json
Labels: maintenance-task

#1334 Require `iconCategory` if `iconName` is set
  components/accordion/__examples__/base.jsx
  components/accordion/__tests__/accordion.browser-test.jsx
  components/accordion/panel.jsx
  components/app-launcher/section.jsx
  components/button-group/__examples__/icon-group.jsx
  components/button-group/__examples__/more-icon.jsx
  components/button-group/__tests__/button-group.browser-test.jsx
  components/button/__docs__/storybook-stories.jsx
  components/button/__examples__/base-neutral.jsx
  components/button/__examples__/button-icons.jsx
  components/button/__tests__/button.browser-test.jsx
  components/button/check-props.js
  components/button/index.jsx
  components/component-docs.json
  components/data-table/row-actions.jsx
  components/forms/input/inline.jsx
  components/lookup/lookup.jsx
  components/menu-dropdown/__docs__/storybook-stories.jsx
  components/menu-dropdown/__examples__/checkmark.jsx
  components/menu-dropdown/__examples__/custom-trigger.jsx
  components/menu-dropdown/__examples__/default-icon-label.jsx
  components/menu-dropdown/__examples__/default.jsx
  components/menu-dropdown/__examples__/sub-heading.jsx
  components/menu-dropdown/__tests__/dropdown.browser-test.jsx
  components/menu-dropdown/menu-dropdown.jsx
  components/modal/index.jsx
  components/notification/index.jsx
  components/page-header/__docs__/storybook-stories.jsx
  components/page-header/__examples__/object-home.jsx
  components/page-header/__examples__/record-home.jsx
  components/page-header/__examples__/related-list.jsx
  components/page-header/__tests__/page-header.browser-test.jsx
  components/popover/popover.jsx
  components/split-view/__examples__/base-multiple.jsx
  components/split-view/__examples__/base.jsx
  components/split-view/__examples__/custom-Item-list.jsx
  components/split-view/__examples__/external-state.jsx
  components/tooltip/__examples__/button-group.jsx
  components/tree/private/branch.jsx
  components/tree/private/item.jsx
  package-lock.json
  package.json
Labels: current sprint, icon

#1368 Fix image snapshots
  package-lock.json
  package.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-inital-blank-story-placeholder-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-accordion-base-1-snap.png
Labels: test task

#1381 Switch xml2json to xml2js in tooling
  package-lock.json
  package.json
  scripts/inline-icons.js
Labels: maintenance-task

#1383 Improve Storyshots tests experience
  app.js
  package.json
  scripts/heroku-postbuild.sh
  tests/story-based-tests.snapshot-test.js
Labels: maintenance-task, test task

#1386 Remove compact prop from DataTable #1189
  components/component-docs.json
  components/data-table/__examples__/basic.jsx
  components/data-table/__tests__/__snapshots__/data-table.snapshot-test.jsx.snap
  components/data-table/check-props.js
  components/data-table/index.jsx
Labels: cla:missing

#1379 Tree bug fixes introduced by keyboard navigation
  components/component-docs.json
  components/tree/__docs__/storybook-stories.jsx
  components/tree/__examples__/default.jsx
  components/tree/__tests__/tree.browser-test.jsx
  components/tree/index.jsx
  components/tree/private/branch.jsx
  components/tree/private/item.jsx
  utilities/sample-data/tree/index.jsx
  utilities/sample-data/tree/sample-nodes-with-initial-state.jsx
Labels: tree

#1392 Align button group example with SLDS example
  components/button-group/__examples__/icon-group.jsx
  components/button-group/__tests__/__snapshots__/button-group.snapshot-test.jsx.snap
Labels: button-group

#1389 Request icons (console warning) with HTTP GET so webpack dev server doesn't 404
  utilities/warning/url-exists.js
Labels: cla:signed

#1385 Data Table header cell markup fixes
  .gitignore
  components/data-table/__tests__/__snapshots__/data-table.snapshot-test.jsx.snap
  components/data-table/index.jsx
  components/data-table/private/head.jsx
  components/data-table/private/header-cell.jsx
  components/story-based-tests.js
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fluid-layout-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: data-table

#1401 Test concurrent
  .travis.yml
  package-lock.json
  package.json
Labels: maintenance-task
