Repository salesforce/design-system-react, pull requests merged in 2018-09, with the labels that each got.

#1530 Button: Add style prop
  components/button/__tests__/button.browser-test.jsx
  components/button/index.jsx
  components/component-docs.json
Labels: button, cla:signed

#1520 fix dialog popper position bug in combobox search scenario
  components/utilities/dialog/index.jsx
Labels: cla:signed

#1534 Publish 0.8.23 release
  RELEASENOTES.md
  patch.md
Labels: cla:signed

#1536 Release Build: Copy files not transpiled
  scripts/dist.sh
Labels: documentation

#1543 Add Brand Band export to index
  components/index.js
Labels: brand-band

#1540 Adds `onRequestIconPath` to IconSettings
  components/icon-settings/__docs__/site-stories.js
  components/icon-settings/__docs__/storybook-stories.jsx
  components/icon-settings/__examples__/on-request-icon-path.jsx
  components/icon-settings/index.jsx
  components/utilities/utility-icon/check-props.js
  components/utilities/utility-icon/index.jsx
Labels: cla:signed, icon

#1532 Fixes DataTable fixed layout width prop issue
  components/data-table/__docs__/site-stories.js
  components/data-table/__docs__/storybook-stories.jsx
  components/data-table/__examples__/basic-fixed-layout.jsx
  components/data-table/__tests__/__snapshots__/data-table.snapshot-test.jsx.snap
  components/data-table/__tests__/data-table.snapshot-test.jsx
  components/data-table/private/header-cell.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fixed-layout-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: cla:signed, data-table

#1555 Make eslint plugin for SLDS external
  .eslintrc.json
  eslint-plugin/package.json.txt
  package-lock.json
  package.json
Labels: scale and productivity

#1556 Convert Dropdown to ES6 class
  components/menu-dropdown/menu-dropdown.jsx
  utilities/key-buffer.js
  utilities/keyboard-navigable-menu.js
  utilities/keyboard-navigate.js
Labels: menu-dropdown

#1552 [IE 11] Do not dismiss combobox lookup menu when clicking on menu scrollbar
  components/combobox/combobox.jsx
  components/combobox/index.jsx
Labels: cla:signed

#1538 Remove Mocha console errors
  components/accordion/__tests__/accordion.browser-test.jsx
  components/app-launcher/__tests__/app-launcher.browser-test.jsx
  components/app-launcher/__tests__/tile.browser-test.jsx
  components/avatar/__tests__/avatar.browser-test.jsx
  components/button/__tests__/button.browser-test.jsx
  components/combobox/__tests__/combobox.browser-test.jsx
  components/forms/input/inline.jsx
  components/global-header/__docs__/storybook-stories.jsx
  components/global-header/dropdown.jsx
  components/global-header/profile.jsx
  components/index.js
  components/input/__tests__/input.browser-test.jsx
  components/lookup/__tests__/lookup.browser-test.jsx
  components/lookup/lookup.jsx
  components/media-object/__tests__/media-object.browser-test.jsx
  components/menu-dropdown/__tests__/dropdown.browser-test.jsx
  components/menu-dropdown/menu-dropdown.jsx
  components/menu-picklist/__tests__/picklist-base.browser-test.jsx
  components/menu-picklist/index.jsx
  components/modal/__tests__/modal.browser-test.jsx
  components/notification/__tests__/notification.browser-test.jsx
  components/page-header/__tests__/page-header.browser-test.jsx
  components/pill/__tests__/pill.browser-test.jsx
  components/tabs/index.jsx
  components/textarea/__tests__/textarea.browser-test.jsx
  components/tree/__tests__/tree.browser-test.jsx
  components/utilities/dialog/index.jsx
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  tests/browser-tests-app.js
Labels: current sprint, test task

#1565 Publish 0.8.26 release
  RELEASENOTES.md
  patch.md
Labels: cla:signed
