Repository salesforce/design-system-react, pull requests merged in 2018-07, with the labels that each got.

#1438 Document copying over SLDS fonts to public
  docs/create-react-app.md
Labels: cla:signed

#1439 Bugfix for Inconsistent Alert Icon
  components/alert/__examples__/error.jsx
  components/alert/__tests__/__snapshots__/alert.snapshot-test.jsx.snap
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-accordion-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fluid-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-assistive-heading-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-with-stencil-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-highlighted-search-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-initial-expanded-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-large-dataset-300-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-multiple-selection-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-no-branch-select-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-overflow-hidden-1-snap.png
Labels: cla:signed

#1426 Make Slider a controlled component
  components/slider/__examples__/base.jsx
  components/slider/__tests__/__snapshots__/slider.snapshot-test.jsx.snap
  components/slider/__tests__/slider.browser-test.jsx
  components/slider/index.jsx
  components/utilities/dialog/index.jsx
Labels: cla:signed

#1442 Update Tree branch and item to use new SLDS HTML tags
  components/tree/private/branch.jsx
  components/tree/private/item.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-assistive-heading-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-with-stencil-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-highlighted-search-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-initial-expanded-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-large-dataset-300-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-multiple-selection-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-no-branch-select-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-overflow-hidden-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: tree

#1462 Update create-react-app.md
  docs/create-react-app.md
Labels: cla:signed

#1459 Menu Dropdown Value Change
  components/menu-dropdown/menu-dropdown.jsx
Labels: menu-dropdown

#1464 Fix Datepicker Year Picklist Display Issue
  components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
  components/date-picker/private/year-picklist.jsx
Labels: cla:signed

#1460 Add warning when Settings.setAppElement is not set.
  components/app-launcher/index.jsx
  components/component-docs.json
  components/modal/index.jsx
  utilities/warning/check-app-element-set.js
Labels: modal

#1471 Revert to npm install from npm ci
  .travis.yml
Labels: maintenance-task, test task

#1457 Prefer object spread eslint rule
  .eslintrc.json
  docs/browser-compatibility.md
  package.json
  webpack.config.dist.js
Labels: maintenance-task

#1376 Fixed problem with progress indicator/assistive-text
  components/progress-indicator/__docs__/storybook-stories.jsx
  components/progress-indicator/__examples__/default.jsx
  components/progress-indicator/__examples__/step-error.jsx
  components/progress-indicator/index.jsx
  components/progress-indicator/private/progress-bar.jsx
  components/progress-indicator/private/step.jsx
  components/story-based-tests.js
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-accordion-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fluid-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-2-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-3-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-4-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-with-disabled-steps-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-base-with-many-steps-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-completed-progress-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-in-a-modal-with-step-error-needs-dom-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-progress-indicator-step-error-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-with-stencil-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-highlighted-search-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-initial-expanded-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-large-dataset-300-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-multiple-selection-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-no-branch-select-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-overflow-hidden-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  tests/story-based-tests.snapshot-test.js
Labels: accessibility, cla:signed, progress-indicator

#1479 Add preset package.json
  preset/package.json.txt
Labels: documentation
