Repository salesforce/design-system-react, pull requests merged in 2018-06, with the labels that each got.

#1357 overflowBoundaryElement Dropdown with align=right uses max-width instead of inherited children width
  components/utilities/dialog/index.jsx
Labels: cla:signed

#1411 Upgrade Babel and Jest
  .babelrc
  components/accordion/__tests__/__snapshots__/accordion.snapshot-test.jsx.snap
  components/alert/__tests__/__snapshots__/alert.snapshot-test.jsx.snap
  components/avatar/__tests__/__snapshots__/avatar.snapshot-test.jsx.snap
  components/button-group/__tests__/__snapshots__/button-group.snapshot-test.jsx.snap
  components/combobox/__tests__/__snapshots__/combobox.snapshot-test.jsx.snap
  components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
  components/forms/checkbox/__tests__/__snapshots__/checkbox.snapshot-test.jsx.snap
  components/menu-picklist/__tests__/__snapshots__/menupicklist.snapshot-test.jsx.snap
  components/pill/__tests__/__snapshots__/pill.snapshot-test.jsx.snap
  components/radio-button-group/__tests__/__snapshots__/radio-button-group.snapshot-test.jsx.snap
  components/radio-group/__tests__/__snapshots__/radio-group.snapshot-test.jsx.snap
  components/slider/__tests__/__snapshots__/slider.snapshot-test.jsx.snap
  components/split-view/__tests__/__snapshots__/split-view.snapshot-test.jsx.snap
  components/toast/__tests__/__snapshots__/toast.snapshot-test.jsx.snap
  karma.conf.js
  package-lock.json
  package.json
  patch.md
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: maintenance-task

#1409 Update SLDS version to 2.6.0
  package-lock.json
  package.json
Labels: current sprint, maintenance-task

#1406 Update tree example to be hashmap in order to promote immutability
  components/index.js
  components/story-based-tests.js
  components/tree/__docs__/dynamic-hashmap.jsx
  components/tree/__docs__/storybook-stories.jsx
  components/tree/__examples__/default.jsx
  components/tree/__tests__/tree.browser-test.jsx
  components/tree/check-props.js
  components/tree/index.jsx
  components/tree/private/branch.jsx
  components/tree/private/item.jsx
  package-lock.json
  package.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-assistive-heading-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-base-with-stencil-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-highlighted-search-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-initial-expanded-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-large-dataset-300-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-multiple-selection-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-no-branch-select-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tree-overflow-hidden-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  utilities/log.js
  utilities/sample-data/tree/index.jsx
  utilities/sample-data/tree/nodes-base.jsx
  utilities/sample-data/tree/nodes-with-initial-state.jsx
  utilities/sample-data/tree/nodes-with-large-dataset.js
  utilities/sample-data/tree/sample-nodes-with-initial-state.jsx
  utilities/sample-data/tree/sample-nodes-with-large-dataset.js
Labels: tree

#1421 Document component composition with prop spread
  docs/codebase-overview.md
Labels: documentation

#1415 Add tabIndex prop to MenuDropdown
  components/component-docs.json
  components/menu-dropdown/__docs__/storybook-stories.jsx
  components/menu-dropdown/__examples__/custom-trigger.jsx
  components/menu-dropdown/menu-dropdown.jsx
Labels: menu-dropdown

#1405 Remove deprecated Picklist from codebase
  components/date-picker/__tests__/__snapshots__/datepicker.snapshot-test.jsx.snap
  components/date-picker/private/year-picklist.jsx
  components/filter/__docs__/storybook-stories.jsx
  components/filter/__examples__/error.jsx
  components/filter/__examples__/locked.jsx
  components/filter/__examples__/new.jsx
  components/filter/__examples__/permanant.jsx
  components/filter/__tests__/__snapshots__/filter.snapshot-test.jsx.snap
  components/modal/__docs__/storybook-stories.jsx
  components/modal/__examples__/menu-contents.jsx
Labels: cla:signed

#1413 Added dropdown option to DataTableRowActions
  components/data-table/__examples__/advanced.jsx
  components/data-table/__tests__/data-table.browser-test.jsx
  components/data-table/row-actions.jsx
Labels: data-table

#1428 Fixing JS errors in tree accessibility
  components/tree/private/branch.jsx
Labels: cla:signed

#1424 Use Fetch for url-exists, if available
  utilities/warning/url-exists.js
Labels: cla:signed

#1432 Add Object.assign to list of required polyfills
  docs/browser-compatibility.md
Labels: cla:signed
