Repository salesforce/design-system-react, pull requests merged in 2018-10, with the labels that each got.

#1554 Tooltip: Align learn more variant with SLDS
  components/tooltip/index.jsx
Labels: tooltip

#1579 Hotfix DataTable stackedHorizontal className.
  components/data-table/index.jsx
Labels: cla:signed

#1574 Prop style for alert
  components/alert/__docs__/storybook-stories.jsx
  components/alert/__examples__/custom-style.jsx
  components/alert/__tests__/alert.browser-test.jsx
  components/alert/index.jsx
  components/component-docs.json
Labels: cla:signed

#1575 Toast new prop style
  components/component-docs.json
  components/toast/__docs__/storybook-stories.jsx
  components/toast/__examples__/custom-style.jsx
  components/toast/__tests__/toast.browser-test.jsx
  components/toast/index.jsx
Labels: cla:signed

#1585 Radio: Add ref, data attribute, and className
  components/component-docs.json
  components/menu-dropdown/menu-dropdown.jsx
  components/radio/__docs__/storybook-stories.jsx
  components/radio/index.jsx
  components/storybook-stories.js
  utilities/get-data-props.js
Labels: cla:signed, radio

#1572 Dialog: Remove isNaN gaurds since ‘inherit’ is not a number
  components/utilities/dialog/index.jsx
Labels: date-picker

#1567 Prevent scroll on focus in portal popovers
  components/utilities/dialog/index.jsx
  components/utilities/dialog/portal.jsx
  utilities/dom-element-focus.js
Labels: filter, panel, popover

#1570 Vertical Nav: Update SLDS markup/classes
  components/vertical-navigation/__tests__/__snapshots__/navigation.snapshot-test.jsx.snap
  components/vertical-navigation/index.jsx
  components/vertical-navigation/private/item.jsx
Labels: vertical-navigation

#1598 Adding missing docs.json
  components/brand-band/docs.json
  components/button-group/docs.json
  components/card/docs.json
Labels: documentation

#1602 fix typo in spinner example
  components/spinner/__examples__/default.jsx
Labels: cla:signed

#1586 Update page header markup
  components/page-header/__docs__/storybook-stories.jsx
  components/page-header/private/base/index.jsx
  components/page-header/private/detail-block.jsx
  components/page-header/private/info.jsx
  components/split-view/__tests__/__snapshots__/split-view.snapshot-test.jsx.snap
Labels: page-header

#1611 Add Color Picker to 0.8.x branch
  components/button/index.jsx
  components/color-picker/__docs__/site-stories.js
  components/color-picker/__docs__/storybook-stories.jsx
  components/color-picker/__examples__/default.jsx
  components/color-picker/__tests__/__snapshots__/color-picker.snapshot-test.jsx.snap
  components/color-picker/__tests__/color-picker.browser-test.jsx
  components/color-picker/__tests__/color-picker.snapshot-test.jsx
  components/color-picker/check-props.js
  components/color-picker/index.jsx
  components/color-picker/private/custom-color-form.jsx
  components/color-picker/private/custom-color.jsx
  components/color-picker/private/hsv-color.jsx
  components/color-picker/private/swatch-option.jsx
  components/color-picker/private/swatch-picker.jsx
  components/color-picker/private/swatch.jsx
  components/component-docs.json
  components/date-picker/date-picker.jsx
  components/index.js
  components/popover/popover.jsx
  components/radio-button-group/index.jsx
  components/radio/index.jsx
  components/storybook-stories.js
  package-lock.json
  package.json
  utilities/color.js
  utilities/constants.js
Labels: colorpicker

#1616 Color Picker: Fixing bug when transparent swatch cannot be set
  components/color-picker/__docs__/storybook-stories.jsx
  components/color-picker/__tests__/__snapshots__/color-picker.snapshot-test.jsx.snap
  components/color-picker/__tests__/color-picker.snapshot-test.jsx
  components/color-picker/check-props.js
  components/color-picker/docs.json
  components/color-picker/index.jsx
  components/color-picker/private/hsv-color.jsx
  components/color-picker/private/swatch-option.jsx
  components/color-picker/private/swatch-picker.jsx
  components/icon-settings/__examples__/on-request-icon-path.jsx
  components/radio/index.jsx
  components/story-based-tests.js
  components/utilities/utility-icon/check-props.js
  components/utilities/utility-icon/index.jsx
  package-lock.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-disabled-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-menu-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-tab-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-validator-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-hidden-input-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-outer-input-in-error-state-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-swatch-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-working-color-input-in-error-state-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: colorpicker

#1622 Bring 0.8x fixes into master branch and release 0.9 version
  RELEASENOTES.md
  components/color-picker/__docs__/storybook-stories.jsx
  components/color-picker/__tests__/__snapshots__/color-picker.snapshot-test.jsx.snap
  components/color-picker/__tests__/color-picker.snapshot-test.jsx
  components/color-picker/check-props.js
  components/color-picker/index.jsx
  components/color-picker/private/hsv-color.jsx
  components/color-picker/private/swatch-option.jsx
  components/color-picker/private/swatch-picker.jsx
  components/radio/index.jsx
  components/story-based-tests.js
  minor.md
  package-lock.json
  package.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-disabled-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-menu-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-tab-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-validator-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-hidden-input-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-outer-input-in-error-state-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-swatch-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-working-color-input-in-error-state-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: maintenance-task

#1619 Clear toast duration timeout in componentWillUnmount().
  components/toast/index.jsx
Labels: cla:signed, toast

#1620 Do not check tooltip isTriggerTabbable if no children.
  components/tooltip/check-props.js
Labels: cla:signed
