Repository salesforce/design-system-react, pull requests merged in 2019-03, with the labels that each got.

#1781 Improve docs for codebase-overview.md and CONTRIBUTING.md
  CONTRIBUTING.md
  docs/codebase-overview.md
Labels: cla:signed

#1793 Return null if options is empty
  components/pill-container/index.jsx
Labels: cla:signed

#1784 Remove non-breaking text from popover examples
  components/tooltip/__docs__/storybook-stories.jsx
Labels: cla:signed

#1779 fixed error icon from warning icon to error icon
  components/input/__examples__/error.jsx
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: cla:signed, forms: input

#1803 Contributing docs: Add new components to package.json
  CONTRIBUTING.md
  docs/codebase-overview.md
Labels: cla:signed, documentation

#1794 Update README.md to run install command in right directory while setting up the code base locally
  README.md
Labels: cla:signed

#1799 Input: Add node to proptypes in forms/private/label
  components/forms/private/label.jsx
Labels: forms: input

#1790 DataTable: Add top border to fixed header tables
  components/component-docs.json
  components/data-table/index.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-single-select-fixed-header-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-advanced-single-select-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fixed-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-basic-fluid-layout-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-data-table-fixed-header-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: data-table

#1692 Popover: Add Error and Warning Variants
  components/popover/__docs__/site-stories.js
  components/popover/__docs__/storybook-stories.jsx
  components/popover/__examples__/alternative-header.jsx
  components/popover/__examples__/controlled-with-footer.jsx
  components/popover/__examples__/error.jsx
  components/popover/__examples__/header.jsx
  components/popover/__examples__/warning.jsx
  components/popover/popover.jsx
  components/story-based-tests.js
  components/utilities/dialog/portal.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-alignment-button-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-alignment-button-icon-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-alternative-header-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-controlled-w-footer-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-error-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-error-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-header-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-styling-dev-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-warning-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-warning-open-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: current sprint, popover

#1821 Require React >16.3
  components/accordion/__tests__/accordion.browser-test.jsx
  components/app-launcher/__tests__/section.browser-test.jsx
  components/app-launcher/__tests__/tile.browser-test.jsx
  components/split-view/__tests__/split-view.listbox.header.browser-test.jsx
  package-lock.json
  package.json
Labels: maintenance-task, scale and productivity

#1734 Refactor Global header for prod status
  components/combobox/combobox.jsx
  components/component-docs.json
  components/global-header/__docs__/storybook-stories.jsx
  components/global-header/__examples__/default.jsx
  components/global-header/__tests__/global-header.browser-test.jsx
  components/global-header/button.jsx
  components/global-header/check-props.js
  components/global-header/docs.json
  components/global-header/dropdown.jsx
  components/global-header/favorites.jsx
  components/global-header/help.jsx
  components/global-header/index.jsx
  components/global-header/notifications.jsx
  components/global-header/profile.jsx
  components/global-header/search.jsx
  components/global-header/setup.jsx
  components/global-header/task.jsx
  components/index.js
  components/menu-dropdown/check-props.js
  components/menu-dropdown/menu-dropdown.jsx
  components/popover/check-props.js
  components/popover/popover.jsx
  package.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-entity-icon-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-entity-initials-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-user-icon-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-user-initials-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-global-header-doc-site-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-global-header-fewer-elements-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-global-header-search-navigation-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-global-header-with-custom-avatar-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  utilities/constants.js
  utilities/warning/has-children-without-display-name-of.js
  utilities/warning/one-of-component.js
Labels: current sprint, global-header

#1860 SLDS update to 2.8.x and store image snapshots when tests fail
  components/data-table/__examples__/advanced-single-select.jsx
  components/data-table/__examples__/advanced.jsx
  components/data-table/__examples__/fixed-header.jsx
  components/tooltip/index.jsx
  package-lock.json
  package.json
  scripts/travis-ci.sh
  scripts/upload-diffs.sh
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: scale and productivity

#1801 Card: add hasNoHeader prop
  components/card/__docs__/storybook-stories.jsx
  components/card/index.jsx
  components/component-docs.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-avatar-entity-icon-2-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-card-w-o-header-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: cla:signed

#1814 removed import bindings which are not used
  components/combobox/__examples__/readonly-multiple.jsx
  components/combobox/__examples__/snapshot/base-open-class-name.jsx
  components/combobox/__examples__/snapshot/base-open.jsx
  components/combobox/__examples__/snapshot/base-selected.jsx
  components/combobox/__examples__/snapshot/readonly-multiple-selection-single-item-selected.jsx
  components/combobox/__examples__/snapshot/readonly-single-selection-selected-open.jsx
  components/combobox/__examples__/snapshot/readonly-single-selection-selected.jsx
  components/combobox/__examples__/snapshot/readonly-single-selection.jsx
  components/filter/__examples__/assistive-text.jsx
  components/filter/__examples__/default.jsx
  components/filter/__examples__/error.jsx
  components/filter/__examples__/locked.jsx
  components/filter/__examples__/new.jsx
  components/filter/__examples__/permanant.jsx
  components/icon/__tests__/icon.snapshot-test.jsx
  components/progress-indicator/__tests__/progress-indicator.browser-test.jsx
Labels: cla:signed

#1828 Condition 'props.hasSpinner' is always true
  components/input/private/inner-input.jsx
Labels: cla:signed

#1856 Used prevState to update state in button-stateful component
  components/button-stateful/index.jsx
Labels: cla:signed

#1845 Use role='status' for Toast
  components/toast/index.jsx
Labels: cla:signed

#1854 Remove unused variables from tests
  components/data-table/__tests__/data-table.browser-test.jsx
  components/filter/__tests__/filter.browser-test.jsx
  components/icon/__tests__/icon.browser-test.jsx
  components/page-header/__docs__/storybook-stories.jsx
  components/progress-indicator/__tests__/progress-indicator.browser-test.jsx
Labels: cla:signed, test task

#1776 Move storyshot DOM snapshots to individual files
  components/accordion/__docs__/__snapshots__/storybook-stories.storyshot
  components/alert/__docs__/__snapshots__/storybook-stories.storyshot
  components/avatar/__docs__/__snapshots__/storybook-stories.storyshot
  components/brand-band/__docs__/__snapshots__/storybook-stories.storyshot
  components/breadcrumb/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-group/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-stateful/__docs__/__snapshots__/storybook-stories.storyshot
  components/button/__docs__/__snapshots__/storybook-stories.storyshot
  components/card/__docs__/__snapshots__/storybook-stories.storyshot
  components/checkbox/__docs__/__snapshots__/storybook-stories.storyshot
  components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
  components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
  components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
  components/filter/__docs__/__snapshots__/storybook-stories.storyshot
  components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/icon/__docs__/__snapshots__/storybook-stories.storyshot
  components/illustration/__docs__/__snapshots__/storybook-stories.storyshot
  components/input/__docs__/__snapshots__/storybook-stories.storyshot
  components/media-object/__docs__/__snapshots__/storybook-stories.storyshot
  components/page-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/pill-container/__docs__/__snapshots__/storybook-stories.storyshot
  components/popover/__docs__/__snapshots__/storybook-stories.storyshot
  components/progress-indicator/__docs__/__snapshots__/storybook-stories.storyshot
  components/tree/__docs__/__snapshots__/storybook-stories.storyshot
  tests/__snapshots__/initial-blank-stories.storyshot
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  tests/story-based-tests.snapshot-test.js
Labels: scale and productivity, test task

#1859 Walkthrough / Walkthrough Action Popover
  components/component-docs.json
  components/popover/__docs__/__snapshots__/storybook-stories.storyshot
  components/popover/__docs__/site-stories.js
  components/popover/__docs__/storybook-stories.jsx
  components/popover/__examples__/custom-target.jsx
  components/popover/__examples__/walkthrough-action.jsx
  components/popover/__examples__/walkthrough.jsx
  components/popover/check-props.js
  components/popover/popover.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-custom-target-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-custom-target-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-walkthrough-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-walkthrough-action-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-walkthrough-action-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-popover-walkthrough-open-1-snap.png
  utilities/warning/incompatible-props.js
Labels: popover
