Repository salesforce/design-system-react, pull requests merged in 2019-02, with the labels that each got.

#1728 Remove warnings from snapshot tests and 404s from browser tests
  components/app-launcher/__examples__/default.jsx
  components/card/__examples__/related-list-with-table.jsx
  components/checkbox/__examples__/error.jsx
  components/checkbox/__examples__/toggle.jsx
  components/combobox/__examples__/base-custom-menu-item.jsx
  components/combobox/__examples__/base-inherit-menu-width.jsx
  components/combobox/__examples__/base-inline-help-tooltip.jsx
  components/combobox/__examples__/base-menu-separator.jsx
  components/combobox/__examples__/base-menu-subheader.jsx
  components/combobox/__examples__/base.jsx
  components/combobox/__examples__/inline-multiple.jsx
  components/combobox/__examples__/inline-single.jsx
  components/combobox/__examples__/required-input-error-state.jsx
  components/combobox/__examples__/snapshot/base-open-class-name.jsx
  components/combobox/__examples__/snapshot/base-open-menu-inheritWidthOf.jsx
  components/combobox/__examples__/snapshot/base-open-menu-sub-header.jsx
  components/combobox/__examples__/snapshot/base-open.jsx
  components/combobox/__examples__/snapshot/inline-multiple-selection-selected.jsx
  components/combobox/__examples__/snapshot/inline-multiple-selection.jsx
  components/combobox/__examples__/snapshot/inline-single-selection-selected.jsx
  components/combobox/__examples__/snapshot/inline-single-selection.jsx
  components/global-header/__examples__/default.jsx
  components/input/__examples__/error.jsx
  components/input/__examples__/icons.jsx
  components/page-header/__docs__/storybook-stories.jsx
  components/page-header/__examples__/object-home.jsx
  components/page-header/__examples__/record-home.jsx
  components/page-header/__examples__/related-list.jsx
  karma.conf.js
Labels: test task

#1722 Menu dropdown propType should support numbers for length
  components/menu-dropdown/menu-dropdown.jsx
  components/utilities/menu-list/index.jsx
Labels: cla:signed

#1725 :star2:(input) styleContainer props
  components/input/index.jsx
Labels: cla:signed

#1721 Add ProgressIndicator tooltipPosition option (with sensible defaults).
  components/component-docs.json
  components/progress-indicator/index.jsx
  components/progress-indicator/private/step.jsx
Labels: cla:signed

#1723 Combobox - allow disabling menu items
  components/combobox/__docs__/storybook-stories.jsx
  components/combobox/__examples__/base-custom-menu-item-disabled.jsx
  components/combobox/__examples__/base-menu-item-disabled-tooltip-open.jsx
  components/combobox/__examples__/base-menu-item-disabled-tooltip.jsx
  components/combobox/__examples__/base-menu-item-disabled.jsx
  components/combobox/__examples__/readonly-menu-item-disabled.jsx
  components/combobox/__tests__/combobox.browser-test.jsx
  components/combobox/combobox.jsx
  components/combobox/private/menu.jsx
  components/component-docs.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-combobox-base-custom-menu-item-disabled-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-combobox-base-menu-item-disabled-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-combobox-base-menu-item-disabled-with-tooltip-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-combobox-base-menu-item-disabled-with-tooltip-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-combobox-readonly-single-menu-item-disabled-1-snap.png
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: combobox

#1740 Define pull request exceptions in more detail
  .github/config.yml
Labels: documentation

#1749 Brand Band documentation update
  components/brand-band/index.jsx
  components/component-docs.json
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: brand-band

#1731 Add automated story-based static accessibility testing workflow and add in-console test documentation
  components/app-launcher/__docs__/storybook-stories.jsx
  components/icon-settings/__docs__/storybook-stories.jsx
  components/modal/__docs__/storybook-stories.jsx
  components/story-based-tests.js
  components/storybook-stories.js
  components/tree/__docs__/storybook-stories.jsx
  karma.conf.js
  package-lock.json
  package.json
  scripts/build-docs.js
  tests/README.md
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
  tests/a11y-config.json
  tests/snapshots-config.json
  tests/story-based-accessibility-tests.js
  tests/story-based-tests.snapshot-test.js
  utilities/execution-environment.js
  utilities/warning/check-app-element-set.js
Labels: accessibility, current sprint, test task

#1754 Datepicker: Clarify MomentJS usage in props/docs
  components/date-picker/date-picker.jsx
Labels: date-picker, documentation

#1745 Fix inheritance of IconSettings context for overflowBoundaryElement Dialog. Add ESLINT skipBlankLines/skipComments max lines rule
  .eslintrc.js
  components/utilities/dialog/index.jsx
Labels: cla:signed

#1757 Add how to release a tag on a fork
  docs/release.md
Labels: documentation

#1760 Add how to release a tag to 1st time PR bot
  .github/config.yml
Labels: documentation

#1748 DataTable: Add prop for sort direction on first time click
  components/data-table/__examples__/advanced.jsx
  components/data-table/__tests__/data-table.browser-test.jsx
  components/data-table/column.jsx
  components/data-table/private/header-cell.jsx
  tests/__snapshots__/story-based-tests.snapshot-test.js.snap
Labels: cla:signed, data-table

#1772 Correct Few Typos in Contributor's Guidelines
  CONTRIBUTING.md
Labels: cla:signed, documentation
