Repository salesforce/design-system-react, pull requests merged in 2019-11, with the labels that each got.

#2398 Fix some React warnings
  components/combobox/private/menu.jsx
  components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
  components/data-table/private/head.jsx
Labels: cla:signed

#2403 Add accessibility statement to readme
  README.md
Labels: accessibility

#2404 Map: Rename Map to LocationMap
  components/builder-header/__tests__/builder-header.browser-test.jsx
  components/button-stateful/__tests__/button-stateful.browser-test.jsx
  components/button/__tests__/button.browser-test.jsx
  components/card/__tests__/card.browser-test.jsx
  components/component-docs.json
  components/data-table/__tests__/data-table.browser-test.jsx
  components/forms/input/__tests__/inline.browser-test.jsx
  components/index.js
  components/input/__tests__/input.browser-test.jsx
  components/location-map/__docs__/storybook-stories.jsx
  components/location-map/__examples__/multiple-locations.jsx
  components/location-map/__examples__/single-location.jsx
  components/location-map/__tests__/location-map.browser-test.jsx
  components/location-map/component.json
  components/location-map/index.jsx
  components/map/component-pre-release.json
  components/menu-dropdown/__tests__/dropdown.browser-test.jsx
  components/menu-picklist/__tests__/picklist-base.browser-test.jsx
  components/modal/__tests__/modal.browser-test.jsx
  components/modal/trigger.jsx
  components/site-stories.js
  components/slider/__tests__/slider.browser-test.jsx
  components/spinner/__tests__/spinner.browser-test.jsx
  components/textarea/__tests__/textarea.browser-test.jsx
  components/tooltip/__tests__/tooltip.browser-test.jsx
  components/welcome-mat/__tests__/welcome-mat.browser-test.jsx
  package.json
  tests/exclude-story-config.js
  utilities/constants.js
Labels: map
