Repository salesforce/design-system-react, pull requests merged in 2019-07, with the labels that each got.

#2141 Welcome mat: Doc site compatibility, Icon prop updates
  components/component-docs.json
  components/index.js
  components/welcome-mat/__examples__/default.jsx
  components/welcome-mat/__examples__/info-only.jsx
  components/welcome-mat/__examples__/steps-complete.jsx
  components/welcome-mat/__examples__/trailhead-complete.jsx
  components/welcome-mat/__examples__/trailhead.jsx
  components/welcome-mat/docs.json
  components/welcome-mat/index.jsx
  components/welcome-mat/tile.jsx
  package.json
Labels: welcome-mat

#2146 Remove image snapshots
  package.json
Labels: test task

#2111 Upgrade SLDS to 2.9.x
  .storybook/preview-head.html
  assets/styles/override.css
  components/brand-band/__docs__/__snapshots__/storybook-stories.storyshot
  components/brand-band/index.jsx
  package-lock.json
  package.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-default-medium-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-image-with-background-size-cover-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-large-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-lightning-blue-theme-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-no-image-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-brand-band-small-1-snap.png
  tests/browser-tests-app.js
  tests/index.html
  tests/story-based-tests.snapshot-test.js
  tests/storyshots-helpers.js
Labels: cla:signed, maintenance-task

#2053 Icon Button: Adds background
  components/button-stateful/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-stateful/__docs__/storybook-stories.jsx
  components/button-stateful/__examples__/icon.jsx
  components/button-stateful/index.jsx
Labels: cla:signed, icon

#1902 Breadcrumb: Ability to add overflow menu
  components/breadcrumb/__docs__/__snapshots__/storybook-stories.storyshot
  components/breadcrumb/__docs__/site-stories.js
  components/breadcrumb/__docs__/storybook-stories.jsx
  components/breadcrumb/__examples__/base-with-overflow-menu.jsx
  components/breadcrumb/index.jsx
  components/component-docs.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-breadcrumb-base-with-overflow-menu-1-snap.png
Labels: bread-crumb, cla:signed

#2160 Demoting Illustration component to `prototype` status
  components/illustration/check-props.js
  components/illustration/docs.json
Labels: illustration

#2134 Icon: Add background theme colors
  components/component-docs.json
  components/icon/__docs__/__snapshots__/storybook-stories.storyshot
  components/icon/__docs__/storybook-stories.jsx
  components/icon/__examples__/product-themes.jsx
  components/icon/index.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-icon-product-themes-1-snap.png
  utilities/product-tokens/icon-backgrounds.js
Labels: cla:signed, icon, page-header

#2077 [UNSUPPORTED PROTOTYPE] Dropdown: Add right to left language support (RTL)
  components/combobox/combobox.jsx
  components/component-docs.json
  components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
  components/menu-dropdown/__docs__/site-stories.js
  components/menu-dropdown/__docs__/storybook-stories.jsx
  components/menu-dropdown/__examples__/custom-trigger.jsx
  components/menu-dropdown/__examples__/default-icon-label.jsx
  components/menu-dropdown/__examples__/default-right-to-left.jsx
  components/menu-dropdown/__examples__/default.jsx
  components/storybook-stories.js
  components/utilities/dialog/index.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-base-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-base-with-icon-dropdown-left-aligned-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-base-with-icon-dropdown-left-aligned-right-to-left-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-base-with-icon-dropdown-right-aligned-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-base-with-icon-dropdown-right-aligned-right-to-left-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-checkmark-right-to-left-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-controlled-w-is-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-custom-content-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-render-inline-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-render-inline-w-nubbins-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-menu-dropdown-render-inline-w-nubbins-right-to-left-1-snap.png
  utilities/dialog-helpers.js
Labels: cla:signed

#2155 Fix for ProgressRing layout issue on IE11
  components/progress-ring/__docs__/__snapshots__/storybook-stories.storyshot
  components/progress-ring/index.jsx
  components/progress-ring/private/ring-shape.jsx
  components/setup-assistant/__docs__/__snapshots__/storybook-stories.storyshot
Labels: cla:signed

#2138 Colorpicker a11y fixes
  components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
  components/color-picker/index.jsx
  components/color-picker/private/custom-color-form.jsx
  components/color-picker/private/custom-color.jsx
  components/color-picker/private/swatch.jsx
  components/tabs/__docs__/__snapshots__/storybook-stories.storyshot
  components/tabs/__docs__/storybook-stories.jsx
  components/tabs/__tests__/tabs.browser-test.jsx
  components/tabs/index.jsx
  components/tabs/private/tab.jsx
  package-lock.json
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-disabled-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-color-picker-menu-open-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-tab-selected-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-custom-validator-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-doc-site-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-hidden-input-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-outer-input-in-error-state-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-predefined-colors-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-swatch-only-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-color-picker-working-color-input-in-error-state-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-conditional-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-custom-tab-contents-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-nested-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-outside-control-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-scoped-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-tab-intercept-panel-select-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-unique-generated-i-ds-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-tabs-with-disabled-tab-1-snap.png
  tests/exclude-story-config.js
Labels: accessibility, colorpicker

#2099 [UNSUPPORTED PROTOTYPE] Colorpicker: Add right to left language support (RTL)
  components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
  components/color-picker/__docs__/storybook-stories.jsx
  components/color-picker/__tests__/color-picker.browser-test.jsx
  components/color-picker/private/swatch-picker.jsx
  components/utilities/dialog/index.jsx
Labels: cla:signed, colorpicker

#2132 [UNSUPPORTED PROTOTYPE] Icon right to left (RTL) support
  components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
  components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
  components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
  components/icon/__docs__/__snapshots__/storybook-stories.storyshot
  components/icon/__docs__/storybook-stories.jsx
  components/icon/__examples__/standard.jsx
  components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
  components/utilities/utility-icon/check-props.js
  components/utilities/utility-icon/index.jsx
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-icon-category-standard-right-to-left-rtl-1-snap.png
Labels: cla:signed, icon

#2166 Fixing DeepScan issues
  components/builder-header/__docs__/storybook-stories.jsx
  components/builder-header/__examples__/after-successful-save.jsx
  components/builder-header/__examples__/base.jsx
  components/builder-header/__examples__/failed-save.jsx
  components/builder-header/__examples__/successful-save.jsx
  components/combobox/__examples__/readonly-multiple.jsx
  components/combobox/__examples__/readonly-single.jsx
  components/combobox/__examples__/snapshot/readonly-multiple-selection.jsx
  components/combobox/__examples__/snapshot/readonly-single-selection-disabled.jsx
  components/combobox/__examples__/snapshot/readonly-single-selection-selected.jsx
  components/data-table/__examples__/basic-fixed-layout.jsx
  components/filter/__examples__/error.jsx
  components/icon/__tests__/icon.browser-test.jsx
  components/illustration/__docs__/storybook-stories.jsx
  components/input/__docs__/storybook-stories.jsx
  components/menu-dropdown/__tests__/dropdown.browser-test.jsx
  components/popover/__examples__/controlled-with-footer.jsx
  components/popover/__examples__/edit-dialog.jsx
  components/progress-ring/__examples__/expired.jsx
  components/radio/__docs__/storybook-stories.jsx
  components/tooltip/__examples__/learn-more.jsx
  components/tree/__docs__/storybook-stories.jsx
  components/tree/__examples__/default.jsx
Labels: maintenance-task

#2172 Remove typo error from all mats
  components/welcome-mat/__examples__/default.jsx
  components/welcome-mat/__examples__/info-only.jsx
  components/welcome-mat/__examples__/splash.jsx
  components/welcome-mat/__examples__/steps-complete.jsx
  components/welcome-mat/__examples__/trailhead-complete.jsx
  components/welcome-mat/__examples__/trailhead.jsx
Labels: cla:signed

#1929 Add Files Component
  components/component-docs.json
  components/files/__docs__/__snapshots__/storybook-stories.storyshot
  components/files/__docs__/site-stories.js
  components/files/__docs__/storybook-stories.jsx
  components/files/__examples__/actions.jsx
  components/files/__examples__/crops.jsx
  components/files/__examples__/default.jsx
  components/files/__examples__/loading.jsx
  components/files/__examples__/no-image.jsx
  components/files/__examples__/no-title.jsx
  components/files/__examples__/with-external-icon.jsx
  components/files/docs.json
  components/files/file.jsx
  components/files/index.jsx
  components/files/more-files.jsx
  components/files/private/file-actions.jsx
  components/files/private/file-figure.jsx
  components/index.js
  components/site-stories.js
  components/spinner/index.jsx
  components/story-based-tests.js
  components/storybook-stories.js
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-cropped-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-default-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-loading-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-w-actions-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-w-external-icon-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-w-o-image-1-snap.png
  tests/__image_snapshots__/story-based-tests-snapshot-test-js-image-snapshots-image-storyshots-slds-files-w-o-title-1-snap.png
  utilities/constants.js
Labels: Files, cla:signed

#2183 Added additional context types
  components/utilities/dialog/index.jsx
Labels: cla:signed

#2185 Prevent literal strings in component source code
  .eslintrc.js
  components/checkbox/index.jsx
  components/date-picker/private/day.jsx
  components/forms/private/label.jsx
  components/lookup/lookup.jsx
  components/menu-picklist/index.jsx
  components/modal/private/manager.jsx
  components/progress-bar/index.jsx
  components/radio-group/index.jsx
  components/slider/index.jsx
  components/split-view/__docs__/__snapshots__/storybook-stories.storyshot
  components/split-view/__tests__/split-view.listbox.header.browser-test.jsx
  components/split-view/listbox.jsx
  components/split-view/private/list-item-with-content.jsx
  components/textarea/index.jsx
  components/tooltip/index.jsx
  components/trial-bar/index.jsx
  components/utilities/deprecated-warning/index.jsx
  components/utilities/label/index.jsx
  components/welcome-mat/index.jsx
  utilities/sample-data/global-navigation-bar/index.jsx
  utilities/sample-data/tree/nodes-base.jsx
Labels: scale and productivity

#2180 Update Icons in Welcome Mat Examples
  components/welcome-mat/__examples__/default.jsx
  components/welcome-mat/__examples__/info-only.jsx
  components/welcome-mat/__examples__/steps-complete.jsx
  components/welcome-mat/__examples__/trailhead-complete.jsx
  components/welcome-mat/__examples__/trailhead.jsx
Labels: cla:signed

#2179 Add Info-Only Class to Welcome Mat Container
  components/welcome-mat/index.jsx
Labels: cla:signed
