Repository salesforce/design-system-react, pull requests merged in 2020-02, with the labels that each got.

#2454 Combobox sort by subheader
  components/combobox/add-subheadings.js
Labels: cla:missing

#2447 Icon bugfix - svg <use xlink:href>
  components/accordion/__docs__/__snapshots__/storybook-stories.storyshot
  components/alert/__docs__/__snapshots__/storybook-stories.storyshot
  components/avatar/__docs__/__snapshots__/storybook-stories.storyshot
  components/badge/__docs__/__snapshots__/storybook-stories.storyshot
  components/breadcrumb/__docs__/__snapshots__/storybook-stories.storyshot
  components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-group/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-stateful/__docs__/__snapshots__/storybook-stories.storyshot
  components/button/__docs__/__snapshots__/storybook-stories.storyshot
  components/button/__tests__/button.browser-test.jsx
  components/card/__docs__/__snapshots__/storybook-stories.storyshot
  components/carousel/__docs__/__snapshots__/storybook-stories.storyshot
  components/color-picker/__docs__/__snapshots__/storybook-stories.storyshot
  components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
  components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
  components/date-picker/__tests__/__snapshots__/datepicker.dom-snapshot-test.jsx.snap
  components/expandable-section/__docs__/__snapshots__/storybook-stories.storyshot
  components/expression/__docs__/__snapshots__/storybook-stories.storyshot
  components/files/__docs__/__snapshots__/storybook-stories.storyshot
  components/filter/__docs__/__snapshots__/storybook-stories.storyshot
  components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/icon/__docs__/__snapshots__/storybook-stories.storyshot
  components/icon/__tests__/icon.browser-test.jsx
  components/input/__docs__/__snapshots__/storybook-stories.storyshot
  components/input/__docs__/search/__snapshots__/storybook-stories.storyshot
  components/media-object/__docs__/__snapshots__/storybook-stories.storyshot
  components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
  components/page-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/panel/__tests__/__snapshots__/filtering.dom-snapshot-test.jsx.snap
  components/pill-container/__docs__/__snapshots__/storybook-stories.storyshot
  components/pill/__docs__/__snapshots__/storybook-stories.storyshot
  components/popover/__docs__/__snapshots__/storybook-stories.storyshot
  components/progress-indicator/__docs__/__snapshots__/storybook-stories.storyshot
  components/progress-ring/__docs__/__snapshots__/storybook-stories.storyshot
  components/scoped-notification/__docs__/__snapshots__/storybook-stories.storyshot
  components/setup-assistant/__docs__/__snapshots__/storybook-stories.storyshot
  components/split-view/__docs__/__snapshots__/storybook-stories.storyshot
  components/split-view/__tests__/split-view.listbox.header.browser-test.jsx
  components/tabs/__docs__/__snapshots__/storybook-stories.storyshot
  components/toast/__docs__/__snapshots__/storybook-stories.storyshot
  components/tooltip/__docs__/__snapshots__/storybook-stories.storyshot
  components/tree/__docs__/__snapshots__/storybook-stories.storyshot
  components/trial-bar/__docs__/__snapshots__/storybook-stories.storyshot
  components/utilities/utility-icon/index.jsx
  components/visual-picker/__docs__/__snapshots__/storybook-stories.storyshot
Labels: icon

#2468 readme typo fix
  tests/README.md
Labels: cla:signed

#2455 Adding type attribute in the link tag for the CSS stylesheets in storybook
  .storybook/preview-head.html
Labels: cla:signed
