Repository salesforce/design-system-react, pull requests merged in 2021-05, with the labels that each got.

#2863 Add title to combobox options
  components/combobox/__docs__/__snapshots__/storybook-stories.storyshot
  components/combobox/private/menu.jsx
Labels: cla:signed

#1755 DataTable: Keyboard navigation
  components/accordion/__docs__/__snapshots__/storybook-stories.storyshot
  components/breadcrumb/__docs__/__snapshots__/storybook-stories.storyshot
  components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/button-group/__docs__/__snapshots__/storybook-stories.storyshot
  components/button/index.jsx
  components/card/__docs__/__snapshots__/storybook-stories.storyshot
  components/checkbox/index.jsx
  components/data-table/__docs__/__snapshots__/storybook-stories.storyshot
  components/data-table/__docs__/storybook-stories.jsx
  components/data-table/__examples__/advanced-single-select-fixed-header.jsx
  components/data-table/__examples__/advanced-single-select.jsx
  components/data-table/__examples__/advanced.jsx
  components/data-table/__examples__/fixed-header-horizontal-scrolling.jsx
  components/data-table/__examples__/fixed-header.jsx
  components/data-table/__examples__/interactive-elements.jsx
  components/data-table/__tests__/data-table.browser-test.jsx
  components/data-table/cell.jsx
  components/data-table/index.jsx
  components/data-table/interactive-element.jsx
  components/data-table/interactive-link.jsx
  components/data-table/private/cell-context.jsx
  components/data-table/private/cell-fixed.jsx
  components/data-table/private/context-helper.js
  components/data-table/private/head.jsx
  components/data-table/private/header-cell.jsx
  components/data-table/private/link.jsx
  components/data-table/private/mode.js
  components/data-table/private/row.jsx
  components/data-table/private/table-context.jsx
  components/data-table/row-actions.jsx
  components/files/__docs__/__snapshots__/storybook-stories.storyshot
  components/global-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/index.js
  components/menu-dropdown/__docs__/__snapshots__/storybook-stories.storyshot
  components/menu-dropdown/menu-dropdown.jsx
  components/page-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/radio/index.jsx
  components/split-view/__docs__/__snapshots__/storybook-stories.storyshot
  components/tooltip/__docs__/__snapshots__/storybook-stories.storyshot
  components/trial-bar/__docs__/__snapshots__/storybook-stories.storyshot
Labels: data-table

#2869 Fixed issue with child Radio disabled state
  components/radio-group/index.jsx
Labels: cla:signed

#2871 Add BuilderHeaderUtilities
  components/builder-header/__docs__/__snapshots__/storybook-stories.storyshot
  components/builder-header/__docs__/storybook-stories.jsx
  components/builder-header/__examples__/base-with-utilities.jsx
  components/builder-header/index.jsx
  components/builder-header/nav-dropdown.jsx
  components/builder-header/nav-link.jsx
  components/builder-header/nav.jsx
  components/builder-header/utilities.jsx
  components/component-docs.json
  components/index.js
  package.json
  utilities/constants.js
Labels: builder-header

#2867 Add PortalSettings Component to allow custom portal DOM placement
  components/component-docs.json
  components/index.js
  components/portal-settings/__docs__/__snapshots__/storybook-stories.storyshot
  components/portal-settings/__docs__/storybook-stories.jsx
  components/portal-settings/__examples__/default.jsx
  components/portal-settings/__examples__/override.jsx
  components/portal-settings/component.json
  components/portal-settings/index.jsx
  components/utilities/dialog/portal.jsx
  package.json
  utilities/constants.js
Labels: cla:signed
